---
- name: config loadbalancer
  hosts: main
  #remote_user: root

  tasks:
    - name: update apt
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      become: true
    
      #    - name: install haproxy
      #      apt:
      #        name: haproxy
      #        update_cache: true
      #      become: true
      
    - name: install gpg
      apt:
        name: gnupg
        update_cache: true
      become: true

    - name: import haproxy keyrings
      apt_key:
        url: https://haproxy.debian.net/bernat.debian.org.gpg
        state: present
      become: true

    - name: install haproxy repo
      apt_repository:
        repo: deb http://haproxy.debian.net buster-backports-2.5 main
        state: present
        update_cache: yes
      become: true

    - name: install haproxy
      apt:
        name: haproxy
        state: present
        update_cache: true
      become: true

    - name: haproxy config
      ansible.builtin.copy:
        src: static/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: '0644'
        backup: yes
      become: true

    - name: restart haproxy service
      ansible.builtin.systemd:
        name: haproxy.service
        state: restarted
      become: true

      #apt update
      #apt install -y gnupg
      #curl https://haproxy.debian.net/bernat.debian.org.gpg \
      #| gpg --dearmor > /usr/share/keyrings/haproxy.debian.net.gpg
      #echo deb "[signed-by=/usr/share/keyrings/haproxy.debian.net.gpg]" \
      #http://haproxy.debian.net buster-backports-2.5 main \
      # > /etc/apt/sources.list.d/haproxy.list
      #apt update
      #apt install -y haproxy
