---
- name: Setup loadbalancer
  hosts: main

  tasks:
    - name: Update apt
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      become: true
    
    - name: Install GPG
      apt:
        name: gnupg
        update_cache: true
      become: true

    - name: Import HAProxy keyring
      apt_key:
        url: https://haproxy.debian.net/bernat.debian.org.gpg
        state: present
      become: true

      #Select version from https://haproxy.debian.net
    - name: Add HAProxy repo
      apt_repository:
        repo: deb http://haproxy.debian.net buster-backports-2.4 main
        state: present
        update_cache: yes
      become: true

    - name: Install HAProxy
      apt:
        name: haproxy
        state: present
        update_cache: true
        default_release: buster-backports-2.4
      become: true

    - name: Configure HAProxy 
      ansible.builtin.copy:
        src: static/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: '0644'
        backup: yes
      become: true

    - name: Restart HAProxy service
      ansible.builtin.systemd:
        name: haproxy.service
        state: restarted
      ignore_errors:  yes
      become: true
